
# Loads default set of integrations. Do not remove.
default_config:

# Enable zeroconf for mDNS/Bonjour discovery of network devices like HomeKit bridges
zeroconf:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit: !include homekit.yaml


